
server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always
logging:
  level:
    org.springframework.data.r2dbc: DEBUG


